### ISSUE TITLE
Adoption and memory consumption

### ISSUE THREAD

**Issue by goramartin** [lgleim/SchemaTreeRecommender#2]
Hello,
sorry to barge in via github, but I was not sure how to contact you otherwise. I got few questions regarding the recommender, I was thinking about using it in a school project. 

I was wondering if the recommender got somehow integrated and adopted into the Wikidata. I found out a bachelor thesis regarding [A-B testing in production ](https://www.cochez.nl/teaching/supervision/theses/Bachelor_Thesis_Jansone.pdf), but I was not able to find, whether it was actually kept in production.

On the other note, I wanted to ask about memory consuption of the creation and running process. In the paper you wrote that about 60 000 000 items result in 1.3 GB memory consuption of the existing tree. Is that also regarding the preprocessing and tree creation? And what would be your memory expectation for the current data size (roughly 105 000 000 items). I am asking if I am able to run the recommender (preprocessing included) on my laptop with 24GB RAM.

Thank you for any feedback possible.

**Comment by lgleim** [comment]
Hi @goramartin, the project has been developed further in [this repository](https://github.com/martaannaj/RecommenderServer), largely as part of the Bachelor thesis you mentioned. @miselico has been leading that effort most recently and you may best reach out to him on the current status of deployment and performance characteristics. 

From the top of my head, 24 GB RAM sounds fine for Wikidata, even in its current form. 

Tree size significantly depends on (non)uniformity of the properties in the input data set but wikidata is reasonably homogeneous. The original experiments were done on a machine with 64 GB RAM which also handled the 4TB LOD-a-lot dataset without issues. As memory pressure increases your CPU will be spending more and more time waiting for the GO garbage collector to free unused objects during tree creation over and over again (as memory is allocated and deallocated for streamed-in input data). The current implementation may handle memory even better then the code in this repository but there are limits to what GO allows you to optimize without breaking its abstractions. One way or another, you should be more than fine with 24 GB RAM for wikidata.

**Comment by goramartin** [comment]
Thank you very much @lgleim for your insights.
I will definitely try to contact the @miselico.

**Comment by miselico** [comment]
Hi @goramartin , let me know if you encounter issues with the further developed implementation.
When loading wikidata; it loads directly from the json dump, rather than from the RDF dump.

**Comment by goramartin** [comment]
Thank you very mych for your reply @miselico. 
Would it be possible to direct any questions regarding the project towards you if they arise? Maybe through github issues on your project or through media of your liking. I can provide my email: im.goramartin@gmail.com
